spring:
  application:
    name: publication
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: circuit-breaker

resilience4j:
  circuitbreaker:
    instances:
      comments:
        slidingWindowSize: 8
        #minimumNumberOfCalls: 4
        slowCallDurationThreshold: 500
        slowCallRateThreshold: 20

        #failureRateThreshold: 50
        #waitDurationInOpenState: 10s
        #permittedNumberOfCallsInHalfOpenState: 2
        #automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    root: INFO
    com.mrsalustiano.publication: DEBUG
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

client:
  comments:
    url: http://localhost:8082
